---
- name: Make war from sources
  hosts: builder
  become: yes
  become_user: root

  tasks:
    - name: Checkout pkgs is presents
      apt:
        pkg:
          - docker.io
          - default-jdk
          - maven
          - python3-pip
        state: present
        update_cache: yes

    - name: Checkout docker (phyton)
      pip:
        name: docker
        state: present
      #  executable: pip3

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Clone git
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
        dest: /home/ubuntu/src

    - name: Build app
      shell: mvn package
      args:
        chdir: /home/ubuntu/src

    - name: Login DockerHub
      docker_login:
        username: murashovs
        password: 9a8dfb44-b795-4fe4-be77-501203f2289b


    - name: Synchronize Dockerfile.
      synchronize:
        src: Dockerfile
        dest: /home/ubuntu/src/target
      # delegate_to: "{{ inventory_hostname }}"



    - name: Make docker image
      command: docker build -t murashovs/web:latest /home/ubuntu/src/target

      #docker_image:
       # name: murashovs/webapp
       # tag: latest
       # push: yes
       # force_tag: yes
       # build:
        #  path: /
       # source: build

    - name: PUSH docker image
      command: docker image push murashovs/web:latest
